option to hide clock and date
pkissling/clock-weather-card pull request #131
Opened 2022-12-21 02:32 UTC by jlambert121

This card is awesome, added it to my tablet display.  I already have time and date already though where I want it so would like to hide it and replace the larger block with the current temperature.

![image](https://user-images.githubusercontent.com/1409929/208806702-e59eec04-a8c9-4944-8139-2f47730824db.png)

2022-12-21 21:07 UTC, jlambert121 commented
I had the ternary operator backwards for the date and didn't notice it.  

![image](https://user-images.githubusercontent.com/1409929/209002858-6559b6de-f734-42d0-833d-1c4d4c859b67.png)

2022-12-22 10:10 UTC, pkissling commented
thanks for the PR. i'll have a look once i'm back from vacation in january

2022-12-22 10:48 UTC, jlambert121 commented
Thanks!  Sorry I couldn't push this over the line - I just haven't done any python before.  Enjoy your vacation!

2023-01-27 16:52 UTC, pkissling approved these changes
hey @jlambert121,
sorry for taking so long with the review. i'm afraid you have to rebase the PR and resolve some merge conflicts before being able to merge it... :(

i only added one suggestion in the PR regarding the feature description in the README.md. other than that the code looks good. i also tested it on my HA instance without any issue.

appreciate your work!

2023-01-27 16:52 UTC, pkissling commented on README.md
> +| hide_clock            | boolean          | **Optional** | Hides the clock from the today section
Hides the clock from the today section and prominently displays the current temperature instead.

2023-01-27 16:53 UTC, pkissling commented
Resolves #141

2023-01-27 17:01 UTC, pkissling commented
> hey @jlambert121, sorry for taking so long with the review. i'm afraid you have to rebase the PR and resolve some merge conflicts before being able to merge it... :(
> 
> i only added one suggestion in the PR regarding the feature description in the README.md. other than that the code looks good. i also tested it on my HA instance without any issue.
> 
> appreciate your work!

i solved the merge conflict for you

2023-01-27 17:04 UTC, pkissling requested changes

2023-01-27 17:04 UTC, pkissling commented on README.md
> +| hide_forecast_section | boolean          | **Optional** | Hides the cards forecast section (lower section), containing the weather forecast
Please also add the properties to https://github.com/pkissling/clock-weather-card#full-configuration

2023-01-29 13:04 UTC, jlambert121 commented
readme updated!

2023-01-29 14:06 UTC, pkissling approved these changes

2023-01-29 14:08 UTC, merged