Add a new time_pattern option.
pkissling/clock-weather-card pull request #242
Opened 2023-10-11 21:59 UTC by cpinkham

- Default new option value to 'HH:mm'
- Remove time_format fallbacks to locale and instead fall through to using time_pattern.
- time_format option can be removed when ready leaving time_pattern to act for time the same as date_pattern acts for date.

References #240

2023-10-12 07:16 UTC, pkissling requested changes

2023-10-12 07:16 UTC, pkissling commented on src/clock-weather-card.ts
> +    // Honor deprecated time_format setting until removed
in order not to introduce a breaking change, the precedence should be `time_pattern` -> `time_format` -> `default`, so please do not remove existing code, but add 

```
if (this.config.time_pattern) {
   return this.toZonedDate(date).toFormat(this.config.time_pattern)
}
```

as the first condition in function `time(...)`

2023-10-12 07:16 UTC, pkissling commented on src/types.ts
> +  time_pattern: string
should be optional

2023-10-12 07:16 UTC, pkissling commented on src/clock-weather-card.ts
> +      time_pattern: config.time_pattern ?? 'HH:mm',
fallback to `undefined` if not provided

2023-10-12 07:16 UTC, pkissling commented on README.md
> +| time_pattern          | string           | **Optional** | Pattern to use for time formatting. If not provided, falls back to a localized default time formatting. See [luxon](https://moment.github.i
precedence `time_pattern` -> `time_format` -> localized default time formatting.
default value should be `null`.

please also add the newly introduced property in `### Full configuration`

2023-10-12 07:17 UTC, pkissling commented
thanks for the PR and your contribution. i requested some changes to make sure we don't breaking existing installations of clock-weather-card after updating to the version including your changes

2023-10-12 16:58 UTC, cpinkham commented
I have all of these ready but have one question about the Full Configuration change before I update the pull request.  Do you want it to be noted in any way in the Full Configuration section indicating time_pattern overrides time_format if both are provided?

Something like:

time_pattern: HH:mm
# Note: time_format is ignored if both time_pattern and time_format are provided
time_format: 24

Thanks for your feedback on this, this is my first time using TypeScript or contributing to HA, so it has been a slight learning curve.

2023-10-13 06:59 UTC, pkissling commented
> I have all of these ready to add to a commit but have one question about the Full Configuration change before I update the pull request. Do you want it to be noted in any way in the Full Configuration section indicating time_pattern overrides time_format if both are provided?
> 
> Something like:
> 
> time_pattern: HH:mm # Note: time_format is ignored if both time_pattern and time_format are provided time_format: 24
> 
> Thanks for your feedback on this, this is my first time using TypeScript or contributing to HA, so it has been a slight learning curve.

no problem, i'm glad your are contributing new features.
i think its sufficient if you mention it in the corresponding property description of https://github.com/pkissling/clock-weather-card#options

2023-10-17 08:38 UTC, pkissling commented
thanks for your contribution!

2023-10-17 08:39 UTC, pkissling approved these changes

2023-10-17 08:39 UTC, merged

2023-10-17 22:38 UTC, cpinkham commented
Sorry, I hadn't commented again yet because I was going to see what I could do about that merge.  I wanted a cleaner request without all the extra commits listed.  Thanks for pulling this in.